SET(CMAKE_SYSTEM_NAME NI-RLT-Linux)
set(NI_ARM_ROOT "/dev/nirlt-linux-arm")
# add compiler to path
LIST(APPEND CMAKE_PROGRAM_PATH "/dev/nirlt-linux-arm/sysroots/i686-nilrtsdk-mingw32/usr/bin/arm-nilrt-linux-gnueabi")
# set compiler (must be called before project/enable)
set(CMAKE_C_COMPILER    "/dev/nirlt-linux-arm/sysroots/i686-nilrtsdk-mingw32/usr/bin/arm-nilrt-linux-gnueabi/arm-nilrt-linux-gnueabi-gcc.exe" CACHE FILEPATH "NI ARM C Compiler")
set(CMAKE_CXX_COMPILER  "/dev/nirlt-linux-arm/sysroots/i686-nilrtsdk-mingw32/usr/bin/arm-nilrt-linux-gnueabi/arm-nilrt-linux-gnueabi-g++.exe" CACHE FILEPATH "NI ARM C++ Compiler")
# set to cross compile
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_CROSSCOMPILING 1)
# setup sysroot (for NI RT cross compiler)
set(CMAKE_SYSROOT       "/dev/nirlt-linux-arm/sysroots/cortexa9-vfpv3-nilrt-linux-gnueabi" CACHE FILEPATH "Path to NI ARM Cross Compiler Sysroot")

set(CMAKE_C_FLAGS_INIT "-march=armv7-a -mfpu=vfpv3  -mfloat-abi=softfp -mcpu=cortex-a9")
set(CMAKE_C_FLAGS_DEBUG_INIT "-g")
set(CMAKE_C_FLAGS_MINSIZEREL_INIT "-Os -DNDEBUG")
set(CMAKE_C_FLAGS_RELEASE_INIT "-O2 -DNDEBUG")
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")
set(CMAKE_CXX_FLAGS_INIT "-march=armv7-a -mfpu=vfpv3 -mfloat-abi=softfp -mcpu=cortex-a9")
set(CMAKE_CXX_FLAGS_DEBUG_INIT "-g")
set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT "-Os -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "-O2 -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")
set(ldflags "-Wl,-O1")
set(CMAKE_EXE_LINKER_FLAGS_INIT ${ldflags})
set(CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT ${ldflags})
set(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL_INIT ${ldflags})
set(CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT ${ldflags})
set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO ${ldflags})
set(CMAKE_SHARED_LINKER_FLAGS_INIT ${ldflags})
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT ${ldflags})
set(CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL_INIT ${ldflags})
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE_INIT ${ldflags})
set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO ${ldflags})
set(CMAKE_MODULE_LINKER_FLAGS_INIT ${ldflags})
set(CMAKE_MODULE_LINKER_FLAGS_DEBUG_INIT ${ldflags})
set(CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL_INIT ${ldflags})
set(CMAKE_MODULE_LINKER_FLAGS_RELEASE_INIT ${ldflags})
set(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO ${ldflags})